### ISSUE TITLE
Plugin doesnt work on 1.19.4. Pls add support for it

### ISSUE THREAD

**Issue by CloudeLecaw** [CraZyRc/WhackaMole#6]
### /version

```txt
Paper 1.19.4
```

### /version WhackaMole

```txt
1.7
```

### Log file

https://pastebin.com/L1RwaN8H

### config.yml

https://pastebin.com/e5AWx0g6

### Description

Errpr on Serverstart:
```
[02:27:10] [Server thread/ERROR]: [WAM] Error initializing plugin 'WhackaMole_1.7.jar' in folder 'plugins' (Is it up to date?)
hidden.dev.jorel.commandapi.exceptions.UnsupportedVersionException: This version of Minecraft is unsupported: 1.19.4
	at hidden.dev.jorel.commandapi.CommandAPIVersionHandler.getNMS(CommandAPIVersionHandler.java:92) ~[WhackaMole_1.7.jar:?]
	at hidden.dev.jorel.commandapi.CommandAPIHandler.<init>(CommandAPIHandler.java:185) ~[WhackaMole_1.7.jar:?]
	at hidden.dev.jorel.commandapi.CommandAPIHandler.getInstance(CommandAPIHandler.java:155) ~[WhackaMole_1.7.jar:?]
	at hidden.dev.jorel.commandapi.CommandAPI.onLoad(CommandAPI.java:180) ~[WhackaMole_1.7.jar:?]
	at whackamole.whackamole.Main.onLoad(Main.java:21) ~[WhackaMole_1.7.jar:?]
	at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:59) ~[paper-1.19.4.jar:git-Paper-453]
	at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:18) ~[paper-1.19.4.jar:git-Paper-453]
	at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:36) ~[paper-1.19.4.jar:git-Paper-453]
	at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:36) ~[paper-1.19.4.jar:git-Paper-453]
	at org.bukkit.craftbukkit.v1_19_R3.CraftServer.loadPlugins(CraftServer.java:423) ~[paper-1.19.4.jar:git-Paper-453]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:273) ~[paper-1.19.4.jar:git-Paper-453]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1103) ~[paper-1.19.4.jar:git-Paper-453]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[paper-1.19.4.jar:git-Paper-453]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by CraZyRc** [comment]
Thanks for mentioning this,
As of right now we are working on a redesign of the plugin with lots of new features, hopefully we will be able to update this to 1.19.4 as well.

So coming asap 😊

**Comment by CraZyRc** [comment]
Done and dusted :)
